name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        working-directory: ./finance-ml
        run: |
          pip install poetry
          poetry install

      - name: Run tests
        working-directory: ./finance-ml
        run: poetry run pytest

  publish:
    needs: test   # attend que les tests soient OK
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'   # uniquement sur main
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Build and publish
        working-directory: ./finance-ml
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          pip install poetry
          poetry publish --build
